// Auto-generated by `pnpm gen:types` — do not edit manually.
// Regenerate after every database migration:
//   pnpm gen:types
//
// Requires a linked Supabase project:
//   supabase link --project-ref <your-project-ref>

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

// Run `pnpm gen:types` to replace this placeholder with your actual database types.
export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
